# version format
version: 2019.1.{build}

# cache the "downloads" folder in the build folder
# refresh cache, if appveyor.yml changes
# trigger cache refresh line: x
#cache:
#  - downloads -> appveyor.yml

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - git config --global core.autocrlf input

install:
  # Upgrade to the latest version of pip to avoid "out of date" warnings
  - C:\python36\python.exe -m pip install --disable-pip-version-check --user --upgrade pip
  - C:\python36\scripts\pip.exe install pyyaml polib pillow future
  
before_build: 
  # download
  - build-scripts\1-download.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\downloads"
  # extract
  - build-scripts\2-extract.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\extracted"
  # Unknown Horizons - create translation files
  - set PATH=%PATH%;C:\projects\uh-installer\build-tools\gettext\bin
  - cd "%APPVEYOR_BUILD_FOLDER%\extracted\unknown-horizons\development"
  - C:\python36\python.exe compile_translation_win.py
  # Unknown Horizons - create atlas files
  - cd "%APPVEYOR_BUILD_FOLDER%\extracted\unknown-horizons"
  - C:\python36\python.exe horizons\engine\generate_atlases.py 1024
  # Unknown Horizons - stripdown 
  # remove all .pyc and .pyo files (rmpyc.sh)
  - del /S /Q *.pyc
  - del /S /Q *.pyo
  - del /Q unknown-horizons.wpr
  - del /Q stage_build_mac.py
  - del /Q CONTRIBUTING.md
  - rd /S /Q tests
  # These files/folders may or may not be present
  #- dir * /s/b | findstr __pycache__ | attrib +h +s +r
  #- rd /S /Q __pycache__
  - del /S /Q "po\*.po~"
  # Removing non-atlas graphics...
  - rd /S /Q content\gfx\base
  - rd /S /Q content\gfx\buildings
  - rd /S /Q content\gfx\units
  - rd /S /Q content\gfx\terrain
  # Not needed folder for gamer version of installer
  - rd /S /Q development
  # Change uh config from dev to release
  - set PATH=%PATH%;C:\projects\uh-installer\build-tools\sed\bin\
  # copy
  - cd "%APPVEYOR_BUILD_FOLDER%
  - build-scripts\3-copy.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\repackage"
  # stripdown
  - build-scripts\4-stripdown.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\repackage"
  
build_script:
  - build-tools\innosetup\iscc /DAPP_VERSION=%APPVEYOR_BUILD_VERSION% installer\uh.iss

artifacts:
  - path: _build\Unknown-Horizons-$(APPVEYOR_BUILD_VERSION)-Setup-VC15-x86.exe
    name: UH-Installer

# deploy to Github Releases on tag push
deploy:
  provider: GitHub
  release: 'Unknown-Horizons-$(APPVEYOR_REPO_TAG_NAME)'
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: '[**Changelog**](https://github.com/unknown-horizons/unknown-horizons/blob/master/doc/CHANGELOG.md)'
  artifact: UH-Installer
  draft: false
  prerelease: false
  force_update: true               # overwrite files of existing release on GitHub
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
  auth_token:                      # encrypted token from GitHub
    secure: jN/6RatSAA/zCF5XUXx/wIeRnpa9yhtQs5VApZWm9Q6TZYtXQCuCEaaANznYMV/B
    
