# version format
version: 2019.1.{build}

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - git config --global core.autocrlf input
  - SET PATH=C:\Python37;%PATH%

install:  
  - python.exe -m pip install --upgrade pip
  - C:\python37\scripts\pip.exe install pyyaml polib pillow future
  
before_build: 
  - build-scripts\1-download.bat
  - build-scripts\2-extract.bat
  - build-scripts\build-uh-translations.bat
  #- build-scripts\build-uh-atlas.bat
  - build-scripts\3-copy.bat
  - build-scripts\4-stripdown.bat
  
build_script:
  - build-tools\innosetup\iscc /DAPP_VERSION=%APPVEYOR_BUILD_VERSION% installer\uh.iss

artifacts:
  - path: Unknown-Horizons-$(APPVEYOR_BUILD_VERSION)-Setup-VC15-x86.exe
    name: UH-Installer

# deploy to Github Releases on tag push
deploy:
  provider: GitHub
  release: 'Unknown-Horizons-$(APPVEYOR_REPO_TAG_NAME)'
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: '[**Changelog**](https://github.com/unknown-horizons/unknown-horizons/blob/master/doc/CHANGELOG.md)'
  artifact: UH-Installer
  draft: false
  prerelease: false
  force_update: true               # overwrite files of existing release on GitHub
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
  auth_token:                      # encrypted token from GitHub
    secure: jN/6RatSAA/zCF5XUXx/wIeRnpa9yhtQs5VApZWm9Q6TZYtXQCuCEaaANznYMV/B

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
