# version format
version: 2017.1.{build}

# cache the "downloads" folder in the build folder
# refresh cache, if appveyor.yml changes
# trigger cache refresh line: x
cache:
  - downloads -> appveyor.yml

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - git config --global core.autocrlf input
  - $env:path -split ";"
  # remove paths
  - cmd: set PATH=%PATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\120;=%
  - cmd: set PATH=%PATH:C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;=%  
  - cmd: set PATH=%PATH:C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;=%  
  - cmd: set PATH=%PATH:C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;=% 
  - cmd: set PATH=%PATH:C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;=%  
  - cmd: set PATH=%PATH:C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;=%  
  - cmd: set PATH=%PATH:C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;=%    
  - $env:path -split ";"

install:
  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.  
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - "pip install pyyaml polib"
  
before_build: 
  # download
  - build-scripts\1-download.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\downloads"
  # extract
  - build-scripts\2-extract.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\extracted"
  # Unknown Horizons - create translation files
  - set PATH="%PATH%;C:\projects\uh-installer\build-tools\gettext\bin"
  - cd "%APPVEYOR_BUILD_FOLDER%\extracted\unknown-horizons\development"
  - python compile_translation_win.py
  # Unknown Horizons - create atlas files
  - cd "%APPVEYOR_BUILD_FOLDER%\extracted\unknown-horizons\horizons\engine"
  - python generate_atlases.py 1024
  # copy
  - build-scripts\3-copy.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\repackage"
  # stripdown
  - build-scripts\4-stripdown.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\repackage"
  
build_script:
  - build-tools\innosetup\iscc /DAPP_VERSION=%APPVEYOR_BUILD_VERSION% installer\uh.iss

after_build:
  - appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\_build\Unknown-Horizons-%APPVEYOR_BUILD_VERSION%-Setup-VC14-x86.exe"
