# version format
version: 2017.1.{build}

# cache the "downloads" folder in the build folder
# refresh cache, if appveyor.yml changes
# trigger cache refresh line: x
cache:
  - downloads -> appveyor.yml

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - git config --global core.autocrlf input

install:
  # Upgrade to the latest version of pip to avoid "out of date" warnings
  - pip install --disable-pip-version-check --user --upgrade pip
  - pip install pyyaml polib pillow
  
before_build: 
  # download
  - build-scripts\1-download.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\downloads"
  # extract
  - build-scripts\2-extract.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\extracted"
  # Unknown Horizons - create translation files
  - set PATH=%PATH%;C:\projects\uh-installer\build-tools\gettext\bin
  - cd "%APPVEYOR_BUILD_FOLDER%\extracted\unknown-horizons\development"
  - python compile_translation_win.py
  # Unknown Horizons - create atlas files
  - cd "%APPVEYOR_BUILD_FOLDER%\extracted\unknown-horizons"
  - python horizons\engine\generate_atlases.py 1024
  # Unknown Horizons - stripdown 
    # remove all .pyc and .pyo files (rmpyc.sh)
    - del /S /Q *.pyc
    - del /S /Q *.pyo
    - del /Q unknown-horizons.wpr
    - del /Q stage_build_mac.py
    - rd /S /Q tests/
    - del /Q CONTRIBUTING.md
    # These files/folders may or may not be present
    - rd /S /Q __pycache__
    - del /S /Q po/*/*.po~
    - del /S /Q po/scenarios/*/*.po~
    # Removing non-atlas graphics...
    - rd /S /Q content/gfx/base
    - rd /S /Q content/gfx/buildings
    - rd /S /Q content/gfx/units
    - rd /S /Q content/gfx/terrain
  # copy
  - cd "%APPVEYOR_BUILD_FOLDER%
  - build-scripts\3-copy.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\repackage"
  # stripdown
  - build-scripts\4-stripdown.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\repackage"
  
build_script:
  - build-tools\innosetup\iscc /DAPP_VERSION=%APPVEYOR_BUILD_VERSION% installer\uh.iss

after_build:
  - appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\_build\Unknown-Horizons-%APPVEYOR_BUILD_VERSION%-Setup-VC14-x86.exe"
